name: avnalytics
version: '1.0'
config-version: 2

profile: avnalytics_profile

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
log-path: logs
target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  avnalytics:
    silver:
      materialized: table
    gold:
      schema: gold
      materialized: table
    admin:
      schema: admin
      materialized: table
