DROP TABLE IF EXISTS SILVER.SILVER_AIRLINES;
CREATE TABLE SILVER.SILVER_AIRLINES (
	AIRLINE_NAME VARCHAR(100),
	IATA_CODE VARCHAR(100),
	ICAO_CODE VARCHAR(100),
    CALLSIGN VARCHAR(100),
    COUNTRY VARCHAR(100),
   	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
