WITH FLIGHT_COUNT AS (
	SELECT
	  SUBSTRING(CALLSIGN, 0, 4) AS AIRLINE_SIGN,
	  COUNT(DISTINCT callsign) AS NUM_OF_FLIGHTS
	FROM {{ source('silver', 'silver_flights') }}
    WHERE callsign IS NOT NULL
      AND callsign != ''
      AND on_ground IS FALSE
	GROUP BY AIRLINE_SIGN
)

SELECT
	AL.AIRLINE_NAME,
	F.NUM_OF_FLIGHTS
FROM FLIGHT_COUNT F JOIN SILVER.SILVER_AIRLINES AL
ON F.AIRLINE_SIGN=AL.ICAO_CODE
