DROP TABLE IF EXISTS ADMIN.ADMIN_JOB_RUNS;

CREATE TABLE ADMIN.ADMIN_JOB_RUNS (
	JOB_RUN_ID SERIAL PRIMARY KEY,
	JOB_NAME VARCHAR(100),
	BATCH_NAME VARCHAR(50),
	BATCH_RUN_ID INTEGER,
	JOB_STATUS VARCHAR(255),
	JOB_RUN_START_TIME TIMESTAMP,
	JOB_RUN_END_TIME TIMESTAMP
)