DROP TABLE IF EXISTS ADMIN.ADMIN_BATCH_RUNS;

CREATE TABLE ADMIN.ADMIN_BATCH_RUNS (
	BATCH_RUN_ID SERIAL PRIMARY KEY,
    BATCH_NAME VARCHAR(255),
	BATCH_STATUS VARCHAR(255),
	BATCH_RUN_START_TIME TIMESTAMP,
	BATCH_RUN_END_TIME TIMESTAMP
)