DROP TABLE IF EXISTS ADMIN.ADMIN_JOB_RUNS;

CREATE TABLE ADMIN.ADMIN_JOB_RUNS (
	BATCH_RUN_ID INTEGER,
    BATCH_NAME VARCHAR(255),
	STATUS VARCHAR(255),
	BATCH_RUN_START_TIME TIMESTAMP,
	BATCH_RUN_END_TIME TIMESTAMP
)