DROP TABLE IF EXISTS ADMIN.ADMIN_JOB_RUNS;

CREATE TABLE ADMIN.ADMIN_JOB_RUNS (
	JOB_RUN_ID INTEGER,
	BATCH VARCHAR(50),
	STATUS VARCHAR(255),
	JOB_RUN_START_TIME TIMESTAMP,
	JOB_RUN_END_TIME TIMESTAMP
)