\connect avnalytics
CREATE SCHEMA IF NOT EXISTS BRONZE AUTHORIZATION asad;
CREATE SCHEMA IF NOT EXISTS SILVER AUTHORIZATION asad;
CREATE SCHEMA IF NOT EXISTS GOLD AUTHORIZATION asad;
CREATE SCHEMA IF NOT EXISTS DQ AUTHORIZATION asad;
