DROP TABLE IF EXISTS BRONZE.BRONZE_AIRLINES;
CREATE TABLE BRONZE.BRONZE_AIRLINES (
	AIRLINE_NAME VARCHAR(100),
	IATA_CODE VARCHAR(100),
	ICAO_CODE VARCHAR(100),
    CALLSIGN VARCHAR(100),
    COUNTRY VARCHAR(100)
)
